# Generated by Django 3.2.8 on 2022-03-22 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDoctorApp', '0004_boggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scrabble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scrabble_letters', models.CharField(max_length=10)),
                ('scrabble_open', models.CharField(max_length=10)),
            ],
        ),
    ]
