# Generated by Django 3.2.8 on 2022-04-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordDoctorApp', '0006_auto_20220405_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordle',
            name='wordle_loc10',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='wordle_loc6',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='wordle_loc7',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='wordle_loc8',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='wordle',
            name='wordle_loc9',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
